#!/usr/bin/env python3

"""
GUI for diabetes prediction.
"""
import sys

from PyQt5.QtWidgets import QWidget, QLabel, QPushButton, QLineEdit, QVBoxLayout, QHBoxLayout, QApplication, QMessageBox
from PyQt5.QtGui import QDoubleValidator, QFont
from PyQt5.QtCore import Qt, QLine

import diabetes

class Diabetes(QWidget):

    def __init__(self) -> None :
        super(Diabetes, self).__init__()
        self.sub_head = QLabel("Patient's   Informations:")
        self.sub_head.setFont(QFont("Times",24, weight=QFont.Bold))
        self.sub_head.setStyleSheet("color: Indigo;")  
        self.l0 = QLineEdit()
        self.l1 = QLineEdit()
        self.l2 = QLineEdit()
        self.l3 = QLineEdit()
        self.l4 = QLineEdit()
        self.l5 = QLineEdit()
        self.l6 = QLineEdit()
        self.l7 = QLineEdit()
        self.l8 = QLineEdit()
        self.t0 = QLabel("Patient's Name:")
        self.t1 = QLabel("Pregnancies:")
        self.t2 = QLabel("Glucose:")
        self.t3 = QLabel("Blood Pressure:")
        self.t4 = QLabel("Skin Thickness:")
        self.t5 = QLabel("Insulin:")
        self.t6 = QLabel("BMI:")
        self.t7 = QLabel("DPF:")
        self.t8 = QLabel("Age:")
        self.r1 = QLabel("(Num. of pregnancies)")
        self.r2 = QLabel("(70-180 mg/dl)")
        self.r3 = QLabel("(80-140mm Hg)")
        self.r4 = QLabel("(10-50mm)")
        self.r5 = QLabel("(15-276mu U/ml)")
        self.r6 = QLabel("(10-50)")
        self.r7 = QLabel("(Diabetes Pedigree Function)")
        self.r8 = QLabel("(In years)")
        self.t0.setFont(QFont("Times",12, weight=QFont.Bold))
        self.t1.setFont(QFont("Times",12, weight=QFont.Bold))
        self.t2.setFont(QFont("Times",13, weight=QFont.Bold))
        self.t3.setFont(QFont("Times",12, weight=QFont.Bold))
        self.t4.setFont(QFont("Times",12, weight=QFont.Bold))
        self.t5.setFont(QFont("Times",12, weight=QFont.Bold))
        self.t6.setFont(QFont("Times",12, weight=QFont.Bold))
        self.t7.setFont(QFont("Times",12, weight=QFont.Bold))
        self.t8.setFont(QFont("Times",12, weight=QFont.Bold))
        self.h0 = QHBoxLayout()
        self.h1 = QHBoxLayout()
        self.h2 = QHBoxLayout()
        self.h3 = QHBoxLayout()
        self.h4 = QHBoxLayout()
        self.h5 = QHBoxLayout()
        self.h6 = QHBoxLayout()
        self.h7 = QHBoxLayout()
        self.h8 = QHBoxLayout()
        self.clbtn = QPushButton("CLEAR")
        self.clbtn.setFixedWidth(100)
        self.submit = QPushButton("SUBMIT")
        self.submit.setFixedWidth(100)
        self.v1_box = QVBoxLayout()
        self.v2_box = QVBoxLayout()
        self.final_hbox = QHBoxLayout()
        self.initui()
        

    def initui(self) -> None:
        """ The gui is created and widgets elements are set here """
        self.v1_box.addWidget(self.sub_head)
        self.v1_box.addSpacing(10)
        self.v1_box.setSpacing(5)
        self.l1.setValidator(QDoubleValidator())
        self.l2.setValidator(QDoubleValidator())
        self.l3.setValidator(QDoubleValidator())
        self.l4.setValidator(QDoubleValidator())
        self.l5.setValidator(QDoubleValidator())
        self.l6.setValidator(QDoubleValidator())
        self.l7.setValidator(QDoubleValidator())
        self.l8.setValidator(QDoubleValidator())
        self.l0.setToolTip("Enter name here")
        self.l1.setToolTip("Number of times pregnant")
        self.l2.setToolTip("Plasma glucose concentration a 2 hours in an oral glucose tolerance test")
        self.l3.setToolTip("Diastolic blood pressure (mm Hg)")
        self.l4.setToolTip("Triceps skin fold thickness (mm)")
        self.l5.setToolTip("2-Hour serum insulin (mu U/ml)")
        self.l6.setToolTip("Body mass index (weight in kg/(height in m)^2)")
        self.l7.setToolTip("Diabetes Pedigree Function")
        self.l8.setToolTip("Age in years")
        self.l0.setFixedSize(285,30)
        self.l1.setFixedSize(40,30)
        self.l2.setFixedSize(40,30)
        self.l3.setFixedSize(40,30)
        self.l4.setFixedSize(40,30)
        self.l5.setFixedSize(40,30)
        self.l6.setFixedSize(40,30)
        self.l7.setFixedSize(40,30)
        self.l8.setFixedSize(40,30)
        self.h0.addWidget(self.t0)
        self.h0.addWidget(self.l0)
        self.v1_box.addLayout(self.h0)
        self.h1.addWidget(self.t1)
        self.h1.addWidget(self.l1)
        self.h1.addWidget(self.r1)        
        self.v1_box.addLayout(self.h1)
        self.h2.addWidget(self.t2)
        self.h2.addWidget(self.l2)
        self.h2.addWidget(self.r2)       
        self.v1_box.addLayout(self.h2)
        self.h3.addWidget(self.t3)
        self.h3.addWidget(self.l3)
        self.h3.addWidget(self.r3)       
        self.v1_box.addLayout(self.h3)
        self.h4.addWidget(self.t4)
        self.h4.addWidget(self.l4)
        self.h4.addWidget(self.r4)      
        self.v1_box.addLayout(self.h4)
        self.h5.addWidget(self.t5)
        self.h5.addWidget(self.l5)
        self.h5.addWidget(self.r5)      
        self.v1_box.addLayout(self.h5)
        self.h6.addWidget(self.t6)
        self.h6.addWidget(self.l6)
        self.h6.addWidget(self.r6)      
        self.v1_box.addLayout(self.h6)
        self.h7.addWidget(self.t7)
        self.h7.addWidget(self.l7)
        self.h7.addWidget(self.r7)      
        self.v1_box.addLayout(self.h7)
        self.h8.addWidget(self.t8)
        self.h8.addWidget(self.l8)
        self.h8.addWidget(self.r8)      
        self.v1_box.addLayout(self.h8)
        self.h9 = QHBoxLayout()
        self.submit.clicked.connect(lambda: self.test_input())
        self.submit.setToolTip("Click to check if patient has diabetes")
        self.clbtn.clicked.connect(lambda: self.clfn())
        self.h9.addWidget(self.submit)
        self.h9.addWidget(self.clbtn)
        self.v1_box.addLayout(self.h9)
        self.report_ui()
        self.final_hbox.addLayout(self.v1_box)
        self.final_hbox.addSpacing(40)
        self.final_hbox.addLayout(self.v2_box)
        self.setLayout(self.final_hbox)

    def report_ui(self):
        self.v2_box.setSpacing(8)
        self.report_subhead = QLabel("DiaCare") 
        self.report_subhead.setStyleSheet("color: DarkGreen;")  
        self.report_subhead.setAlignment(Qt.AlignCenter)
        self.report_subhead.setFont(QFont("Times",24, weight=QFont.Bold))
        self.v2_box.addWidget(self.report_subhead)
        self.details = QLabel("                     Welcome!  \n'DiaCare - The Diabetes Predictor' Please fill all the details carefully and press the submit button to see your desire result.\nThank you for using our application.")
        self.details.setFont(QFont("Arial",13, weight=QFont.Bold))
        self.details.setAlignment(Qt.AlignLeft)
        self.details.setWordWrap(True)
        self.model_details = QLabel("\n\n\n\n\n\n\n\nDiaCare © Fahmid Anabi")
        self.model_details.setWordWrap(True)
        self.v2_box.addWidget(self.details)
        self.results = QLabel(" ")
        self.results.setWordWrap(True)
        self.v2_box.addWidget(self.results)
        self.v2_box.addWidget(self.model_details)

    def clfn(self):
        """ clear all the text fields via clear button"""
        self.l0.clear()
        self.l1.clear()
        self.l2.clear()
        self.l3.clear()
        self.l3.clear()
        self.l4.clear()
        self.l5.clear()
        self.l6.clear()
        self.l7.clear()
        self.l8.clear()
        self.report_subhead.setText("DiaCare")
        self.model_details.setText("\n\n\n\n\n\n\n\nDiaCare © Fahmid Anabi")
        self.results.setText(" ")
        self.details.setText("                     Welcome!  \n'DiaCare - The Diabetes Predictor' Please fill all the details carefully and press the submit button to see your desire result.\nThank you for using our application.")
    

    def test_input(self) -> None:
        """ test for diabetes"""
        my_dict = {"Pregnancies":float(self.l1.text()), "Glucose":float(self.l2.text()),"BloodPressure":float(self.l3.text()), "SkinThickness":float(self.l4.text()), "Insulin": float(self.l5.text()), "BMI":float(self.l6.text()), "DiabetesPedigreeFunction":float(self.l7.text()), "Age":float(self.l8.text())}
        output = diabetes.check_input(my_dict)
      
        self.report_subhead.setText("Report:")
        self.model_details.setText("\n\n\nDiaCare © Fahmid Anabi")
        self.details.setText("Patient's name: {}\nPregnancies: {}\nGlucose: {} \nBlood Pressure: {}\nSkin Thickness: {}\nInsulin: {}\nBMI: {}\nDPF: {}\nAge: {}".format(self.l0.text(), self.l1.text(), self.l2.text(), self.l3.text(),self.l4.text(),self.l5.text(), self.l6.text(),self.l7.text(),self.l8.text()))
        self.details.setAlignment(Qt.AlignLeft)
        self.details.setWordWrap(True)
        #
        if output==0:
            self.results.setText("\nOur diagnosis suggests that patient does not suffers from diabetes.")
            self.results.setStyleSheet("color: green;") 
        else:
            self.results.setText("\nOur diagnosis suggests patient does suffer from diabetes.Please immediatly contact to your doctor.")
            self.results.setStyleSheet("color: red;")   
        self.results.setFont(QFont("Arial",14, weight=QFont.Bold))
            

    def mwindow(self) -> None:
        """ window features are set here and application is loaded into display"""
        self.setFixedSize(898, 422)
        self.setWindowTitle("DiaCare - The Diabetes Predictor")
        self.setStyleSheet("background-color: #e8e8ea ;")
        self.show()


if __name__=="__main__":
    app = QApplication(sys.argv)
    a_window = Diabetes()
    a_window.mwindow()
    sys.exit(app.exec_())
